version: '3.8'

services:
  estadisticas-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estadisticas-vue
    ports:
      - "5174:5174"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - estadisticas-network

networks:
  estadisticas-network:
    driver: bridge
